### PR TITLE
Support Laravel v7.28.3

### PR DESCRIPTION
**Pull request by puntable**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You need to use `^8.1` of this package for Laravel 7.

**Comment by puntable** [comment]
Yes i see now, but would be nice if latest version had backward compatibility with one Laravel major release (i.e. Laravel 7).

**Comment by GrahamCampbell** [comment]
That's not how @vinkla does things.

**Comment by GrahamCampbell** [comment]
Latest versions always require latest laravel.

**Comment by vinkla** [comment]
I wonder if there ever will be a day when Composer solves this by itself.

Thanks for helping out Graham.

**Pull request closed without merging**
