### PR TITLE
Laravel 10 support

### PR DESCRIPTION
**Pull request by vinkla**
This will be merged as soon as the following packages have been updated for Laravel 10:

- `graham-campbell/analyzer`
- `graham-campbell/testbench`
- `graham-campbell/manager`

### CODE REVIEW

**Comment by adampatterson** [comment]
Guess I won't log this 👍

**Comment by RohanSakhale** [comment]
@vinkla when can you merge this?

**Comment by vinkla** [comment]
@RohanSakhale did you not read the pull request description? Instead you took the time to write a comment. As I'm doing now, pointing it out.

**Comment by vinkla** [comment]
The only reason I created this PR is to stop people from spamming the repository. It seems people are too lazy to bother searching the repository: #176, #177

This is free software. It will be released when it will be released. 

[Open Source Maintainers Owe You Nothing](https://mikemcquaid.com/open-source-maintainers-owe-you-nothing/) - [Mike McQuaid](mailto:mike@mikemcquaid.com)

**Comment by RohanSakhale** [comment]
> @RohanSakhale did you not read the pull request description? Instead you took the time to write a comment. As I'm doing now, pointing it out.

Thanks for pointing out, missed reading the dependencies 👍🏻

**Comment by lucidlogic** [comment]
It seems this is blocked by this PR https://github.com/GrahamCampbell/Laravel-Manager/pull/18

**Comment by miladnouri** [comment]
> * graham-campbell

Hi,
All of the packages have been updated.

**Comment by RohanSakhale** [comment]
@vinkla #180 PR for updating the `GrahamCampbell` packages

**Comment by vinkla** [comment]
https://github.com/vinkla/laravel-hashids/releases/tag/11.0.0

**Pull request merged**
