### PR TITLE
Add an interface and trait for Eloquent models

### PR DESCRIPTION
**Pull request by tremby**
These make it a simple process to add methods to Eloquent models to retrieve an instance's hashid, and to find a model based on its hashid.

I find myself frequently adding these to projects, and it'd be nice if they were bundled with the bridge.

I haven't written tests, and they are not thoroughly tested. Before doing any of that I want to gauge your interest in accepting this feature.

### CODE REVIEW

**Comment by tremby** [comment]
Why in the world is StyleCI asking me to indent some docstrings by an extra space?

**Comment by GrahamCampbell** [comment]
StyleCI is correct.

**Comment by tremby** [comment]
No, StyleCI was wrong. Or it was right, but about the wrong thing.

What I had wrong was the indentation of the lines *following* the second and third docstrings. They were indented five spaces. StyleCI was saying *those* lines were fine but that I should indent the preceding docstrings by an extra space to match.

**Comment by tremby** [comment]
Possible discussion points:

- What do you think of how I've handled multiple-integer vs single-integer hashids, and how I've reconciled those with Eloquent's `find` and `findOrFail` methods? In my experience hashids are mostly used to encode single integers (and especially in this context), and so expecting a single integer by default is the right thing to do. Hashids has a design flaws that you can't tell the difference (as far as I know) between a broken hashid and a hashid encoding an empty array, and that you can't tell the difference between encoding a single integer and encoding an array containing one single integer. So my implementation here was the best I could come up with with those constraints. Other possibilities include separate methods to handle the cases where arrays are expected.
- Is throwing an \InvalidArgumentException the right thing to do, in the case where I've done that?
- Should hashid analogues of more of Eloquent's methods be implemented?
- Should there be a way to get from an Eloquent Collection to a hashid encoding its members' primary keys? I wouldn't know how or where to add this, except as a static method taking a collection as an argument, or possibly an override of `newCollection` which uses a surrogate class with an extra method, but both of these seem messy.

**Comment by vinkla** [comment]
Thank you for this pull request! Though, I want to keep this library light and don't add to much custom logic. Personally I don't follow a similar setup when I install Hashids. I use the route model binding in the `RouteServiceProvider` class. Here is an example:

```php
$router->bind('user', function ($value) {
  if (is_numeric($value) && $user = User::find($value)) {
    return $user;
  }

  $decoded = Hashids::connection('users')->decode($value);

  if (isset($decoded[0]) && is_numeric($decoded[0]) && $user = User::find($decoded[0])) {
    return $user;
  }

  throw new NotFoundHttpException('User not found.');
});
```

Again, thanks for creating the pull request and taking the time to write a good description. Though, at the current time I wont merge this pull request.

**Comment by tremby** [comment]
Fair enough.

But don't you then need to repeat that same logic for each model type?

**Comment by vinkla** [comment]
Yeah, could probably optimise it. In this case I only needed it for one model.

**Pull request closed without merging**
