### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by the94air**

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks but I think it is fine the way it is.

**Comment by the94air** [comment]
But it is very annoying

**Comment by GrahamCampbell** [comment]
How so?

**Comment by the94air** [comment]
heyyyy @GrahamCampbell Did we meet before in a Laravel issues maybe?

**Comment by GrahamCampbell** [comment]
> if you forget , this will stop your laravel app if it was live.

The comma is not required if you add it at the end of the list. That was my point.

**Comment by the94air** [comment]
Okay never mind.

**Comment by the94air** [comment]
It's too emprising to see my old terrible pull requests. I apologize if I was annoying at anyhow :smile:

**Pull request closed without merging**
